### ISSUE TITLE
Projenin lisansı nedir ?

### ISSUE THREAD

**Issue by hwpplayer1** [pardus/pardus-power-manager-advanced#2]
Merhaba, proje için teşekkür ederim. Rica etsem hangi lisans ile lisanslandığını ve Copyright ifadesinin ne olduğunu öğrenebilir miyim ?

Teşekkürler, görüşmek üzere, iyi çalışmalar

**Comment by sulincix** [comment]
https://github.com/pardus/pardus-power-manager/blob/master/debian/copyright

Gpl V3
