### ISSUE TITLE
help çıktısının daha açıklayıcı olması hakkında

### ISSUE THREAD

**Issue by hwpplayer1** [pardus/pardus-power-manager-advanced#4]
Merhaba kaynak koddan Ubuntu 22.04 sistemine ppm projesini derleyerek, inşa ederek kurdum.

Aşağıdaki çıktıyı görüyorum. Acaba daha açıklayıcı olabilir mi ?

`hwpplayer1@hwpplayer1-Aspire-A315-24P:/usr/bin$ ./ppm help
['/usr/share/pardus/power-manager/client/cli.py', 'help']
Usage: ppm [set/get] [mode/backlight] (value)`

**Comment by hwpplayer1** [comment]
Deneme amaçlı aşağıdaki gibi işlem yaparak derlenmiş ikiliyi sistemden kaldırdım. Zira systemd hatası veriyordu. Activating diyordu. Aşağıda çıktılar yer almakta 👍🏿 

`hwpplayer1@hwpplayer1-Aspire-A315-24P:~$ sudo systemctl status ppm
● ppm.service - Pardus Power Manager
     Loaded: loaded (/lib/systemd/system/ppm.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Tue 2024-01-23 10:50:22 +03; 535ms ago
    Process: 10002 ExecStart=/usr/libexec/pardus-power-manager (code=exited, status=1/FAILURE)
   Main PID: 10002 (code=exited, status=1/FAILURE)
        CPU: 39ms
`

`hwpplayer1@hwpplayer1-Aspire-A315-24P:~$ sudo rm /usr/bin/ppm
hwpplayer1@hwpplayer1-Aspire-A315-24P:~$ ppm help
Command 'ppm' not found, but there are 17 similar ones.`

**Comment by hwpplayer1** [comment]
Gözlemime göre ppm.service dosyası binary silindikten sonra da durmakta. Acaba bu systemd özelliği mi ? Sonra systemd içine girip servisi sildim. Teşekkürler.

**Comment by sulincix** [comment]
silmek için kullandığınız yöntem nedir.

**Comment by sulincix** [comment]
![Untitled Diagram drawio(1)](https://github.com/pardus/pardus-power-manager/assets/55052890/2833fbc3-e1ed-404c-aded-793cd16bd5ef)

/run/ppm ve /run/user/$UID/ppm/$PID birer write only çalışan fifo olup blocking read olarak okunmaktadır.

Pardus power manager kullanıcı ve servis tarafındaki iletişim şeması bu şekilde.

ppm komutu sadece servisi yönlendirmeye yarar. silseniz bile servis mevcut olmaya devam eder. Onun için servisi ile beraber silmelisiniz.

**Comment by hwpplayer1** [comment]
> silmek için kullandığınız yöntem nedir.

sudo rm ppm.service ile çalıştırdım

**Comment by sulincix** [comment]
Servis dosyalarını silmeden önce servisi durdurup devre dışı yapmalısınız. Systemd bu şekilde çalışıyor.

**Comment by hwpplayer1** [comment]
Öyle yapmıştım gerçi. Ama kafam karışmış olabilir. Teşekkürler bilgi için
